# Generated by Django 3.2.1 on 2021-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=50)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(max_length=1000)),
                ('previous_work', models.TextField()),
                ('facebook_url', models.URLField()),
            ],
        ),
    ]
